### ISSUE TITLE
I can't get gRPC to work

### ISSUE THREAD

**Issue by ercxar** [kirin10000/Xray-script#45]
Hi! First of all thank you for the perfect script.
As mentioned in the title, doesn't matter what I do, I cannot get the gRPC to work. I enabled the option on CF to allow gRPC connection. But on the client I always get the "The underlying connection was closed. An unexpected error occurred on a send." error. It seems it's related to TLS but I tried with all TLS version and for all of them the error is same.
Is there any hidden options on the CF that I need to enable/disable to get it work?
I also should mentioned that everything else works just fine.

Any input would be appreciated.

**Comment by ercxar** [comment]
I figured there is not any option in the app that I'm using to change ALPN in TLS settings. I suspect this might be the cause of my issue.
Any recommended apps for Android/iOS or Windows to be able to fully use gRPC?

**Comment by kirin10000** [comment]
My English is not good, I will try my best to explain.
First, up to now, there is no app support to config`multiMode`, see here(https://xtls.github.io/config/transports/grpc/). So you can't connect with grpc using app, you need to write the json file by yourself, setting the `multiMode` to `true`.
Second, ALPN will not course the connect failed, it only impact possibility of your Xray-server being blocked, because everyone can see the alpn when you connect your Xray-server. The Qv2ray support to config the alpn.

**Comment by ercxar** [comment]
Thank you for the explanation. No worries on the language. English is also not my first language, if you feel comfortable just write in your native language and I will translate it. It's pretty accurate.
Yeah the current issue is, there is almost no app support for gRPC. I had no idea about the `multimod`. I only added `alpn`. To be more secure, should I not add ALPN then? Does it affect the connection to be failed?

**Comment by kirin10000** [comment]
about ALPN:
when using grpc, Xray-client will add "h2" to alpn automatically. if you set the alpn to "http/1.1", it will change to "h2","http/1.1". if you set the alpn to "h2", it will not change. if you don't set alpn, it will be set to "h2","http/1.1" by default.

about `multimod`:
you must set `multimod` to `true` to connect, but defautly it is `false`. Using Qv2ray can config the json file easily
![image](https://user-images.githubusercontent.com/57820613/114500311-590dd300-9c5a-11eb-854b-bf263cd6ba9a.png)

**Comment by feiyue789** [comment]
我的grpc也连接不上，v2rayng自定义配置也不行
